### PR TITLE
Uicleanup

### PR DESCRIPTION
**Pull request by ModProg**
### Added some Dokumentation
Dokumentation of `BlockMeterClient` and `SupressWarning` for `MinecraftClient.getInstance()` in `ClientMeasureBox.java`

### Updated Options UI

1. Wider Buttons (`200` instead of `180`) to support German Text without overflowing:
German Menu
2. Restructure and Translation of menu options using `options.on/off`
3. Changed "Show other user's blocks" to "other user's boxes" (German translation as well)

### CODE REVIEW

**Review by gbl — CHANGES_REQUESTED** [review]
Most of the things I'm comfortable with, however:

- documentation says button with was changed from 180 to 200, but the PR still has 180
- I disagree with renaming `disconnected` and `connected` to `disconnect`/`connect`, these methods are not requests to connect or disconnect, but callbacks to tell BlockMeter that the client has connected to or disconnected from a server

**Comment by ModProg** [comment]
I changed that, what about naming `ClientPlayerDisconnectedMixin` => `ClientPlayerConnectionMixin` as it handles both?

**Comment by ModProg** [comment]
Also what is your preferred way of doing config, I was thinking about using ClothConfig and autoconfig1u, because I will add more complexity with shapes such as Circles and Spheres and will add configuration via ModMenu.
If you want to keep this tool simpler I would release my Fork under an other name.

**Comment by gbl** [comment]
Agree with these changes.

Config: With my other mods, I use my own config system, which I originally wrote for 1.13 and Rift, to be as compatible as possible to the even older 1.12 Forge config system so I was able to update easily. And I kept it alive until now, because some of my mods have a Forge version and a Fabric version, and my config system works with both, so I don't have to care about that when maintaining both loaders.

As for BlockMeter, I didn't think about porting that back to forge; I don't want to take away downloads from the original author who made a Forge version. So there's no general advantage to my own config system. On the other hand, the original author stopped supporting the mod after 1.14.4, so maybe making a Forge version isn't completely unthinkable either.

If you want to give my system a try, check out 

- onInitializeClient in https://github.com/gbl/DurabilityViewer/blob/fabric_1_16/src/main/java/de/guntram/mcmod/durabilityviewer/DurabilityViewer.java, to initialize the system in a mod
- https://github.com/gbl/DurabilityViewer/blob/fabric_1_16/src/main/java/de/guntram/mcmod/durabilityviewer/handler/ConfigurationHandler.java for how to configure a mod
- https://github.com/gbl/DurabilityViewer/blob/fabric_1_16/src/main/java/de/guntram/mcmod/durabilityviewer/handler/MMConfigurationHandler.java for ModMenu integration
- https://github.com/gbl/DurabilityViewer/blob/fabric_1_16/build.gradle to pull classes in

If you know ClothConfig and autoconfig weill, I have no problem with using those.

Also, I'm ok with adding features as long as that doesn't break compatibility with people who don't update, especially the cooperation part. It looks like 1.16.2 will require people to update anyway, so changes to the protocol shouldn't be done before that, and I assume adding spheres won't be able using the current protocol. So, if you want to add those features *now*, I'd ask you to publish under a different name; if you're ok with "BlockMeter has several new features in MC 1.16.2", then I'd put it on my page (or feel free to publish yourself anyway; most of my codebase is from someone else as well, and the mod is under MIT license, so I certainly won't try to stop you!)

**Pull request merged**
